# The Site Configuration

theme: jekyll-theme-chirpy

# Bahasa & zona waktu
lang: id
timezone: Asia/Jakarta

# Identitas situs
title: Bolometu.com
tagline: Catatan, Inspirasi, dan Informasi
description: >-
  Bolometu.com adalah blog pribadi Farhan Cahyadi yang berisi catatan, inspirasi,
  dan informasi seputar teknologi, blogging, dan kehidupan sehari-hari.

# URL utama blog
url: "https://bloghugo.github.io"
baseurl: "/jekyll-pribadi"

# Profil akun
github:
  username: bloghugo   # ganti kalau akun GitHub beda

twitter:
  username: bolometu   # bisa dikosongi kalau tidak pakai

social:
  name: Farhan Cahyadi
  email: farhan@example.com
  links:
    - https://github.com/bloghugo
    # - https://twitter.com/bolometu
    # - https://www.linkedin.com/in/farhan-cahyadi

# Verifikasi webmaster (untuk SEO & Google Search Console)
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
  facebook: 

# Analytics
analytics:
  google:
    id:   # contoh: G-XXXXXXXXXX
  cloudflare:
    id:   # kalau pakai Cloudflare Web Analytics

# Preferensi tampilan (dark/light mode)
theme_mode:   # kosong = otomatis sesuai sistem

# CDN untuk gambar/assets (opsional)
cdn: 

# Avatar sidebar
avatar: "/commons/avatar.jpg"

# Gambar default untuk share di sosial media
social_preview_image: 

# TOC (daftar isi) global
toc: true

# Komentar (pilih salah satu: disqus, utterances, giscus)
comments:
  provider: 
  disqus:
    shortname: 
  utterances:
    repo: 
    issue_term: 
  giscus:
    repo: 
    repo_id: 
    category: 
    category_id: 

# PWA (Progressive Web App)
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: 

# Pagination
paginate: 10

# ------------ Jangan diubah kecuali paham ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/